# Generated by Django 4.1.2 on 2022-12-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_code", models.CharField(max_length=6)),
                ("account_number", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="DebitCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cvv", models.IntegerField()),
                ("card_number", models.CharField(max_length=16)),
                ("expiry_date", models.DateTimeField(verbose_name="date expiry")),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("currency_own", models.CharField(max_length=10)),
                ("currency_req", models.CharField(max_length=10)),
                ("amount_offered", models.FloatField(default=0)),
                ("exchange_rate", models.FloatField()),
                ("publish_date", models.DateTimeField(verbose_name="date published")),
                ("expiry_date", models.DateTimeField(verbose_name="date expiry")),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "bank_account_get",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related_get",
                        to="polls.bankaccount",
                    ),
                ),
                (
                    "bank_account_rec",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related_rec",
                        to="polls.bankaccount",
                    ),
                ),
                (
                    "debit_card_get",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related_get",
                        to="polls.debitcard",
                    ),
                ),
                (
                    "debit_card_rec",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related_rec",
                        to="polls.debitcard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id_rec", models.IntegerField()),
                ("execution_time", models.DateTimeField(verbose_name="execution time")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="polls.offer"
                    ),
                ),
                (
                    "payment_method_get",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related_get",
                        to="polls.paymentdetails",
                    ),
                ),
                (
                    "payment_method_rec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related_rec",
                        to="polls.paymentdetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="offer",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="polls.paymentdetails"
            ),
        ),
    ]
