# Generated by Django 4.1.2 on 2022-12-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_bankaccount_debitcard_offer_paymentdetails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_method_get",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_get",
                to="polls.paymentdetails",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method_rec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_rec",
                to="polls.paymentdetails",
            ),
        ),
    ]
