# Generated by Django 4.1.2 on 2022-12-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_transaction_payment_method_get_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
