# Generated by Django 4.1.2 on 2022-12-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id_rec", models.IntegerField()),
                ("execution_time", models.DateTimeField(verbose_name="execution time")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="polls.offer"
                    ),
                ),
                (
                    "payment_method_get",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_get",
                        to="polls.paymentdetails",
                    ),
                ),
                (
                    "payment_method_rec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_rec",
                        to="polls.paymentdetails",
                    ),
                ),
            ],
        ),
    ]
