# Generated by Django 4.1.2 on 2023-01-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_transaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
